LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS:= optional
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_SRC_FILES := qn8006mod.c
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_MODULE := qn8006.default
include $(BUILD_SHARED_LIBRARY)
